'use strict';

window.CICEK_PAGE_TRANSLATIONS = {
  en: {
    'VAG servis rehberi':'VAG service guide','VAG teknolojisini bilen servis.':'Service that understands VAG technology.',
    'Volkswagen, Audi, Škoda, SEAT ve CUPRA araçların ortak motor, DSG ve elektronik altyapısına odaklanan servis yaklaşımı. Önce teşhis, sonra açık işlem planı ve fiyat onayı.':'A service approach focused on the shared engine, DSG and electronic systems of Volkswagen, Audi, Škoda, SEAT and CUPRA. Diagnosis first, then a clear work plan and price approval.',
    'Yol tarifi':'Directions','09:00–17:00':'09:00–17:00','Online randevu başlangıç saatleri':'Online booking start times','Çoklu hizmet':'Multiple services','Tek randevuda birden fazla işlem':'Several jobs in one booking','Şeffaf onay':'Transparent approval','İşlem öncesi kapsam ve fiyat bilgisi':'Scope and price before work','VAG odağı':'VAG focus','Ortak platform ve teknoloji bilgisi':'Shared platform and technology expertise',
    'Marka uzmanlığı':'Brand expertise','Beş marka,':'Five brands,','ortak teknoloji.':'shared technology.','VAG grubundaki ortak motor, şanzıman ve elektronik sistem bilgisi; arızayı yalnızca belirti üzerinden değil, sistemin tamamı üzerinden değerlendirmeyi sağlar.':'Knowledge of shared VAG engines, transmissions and electronics lets us assess the whole system, not just a symptom.',
    'Golf, Passat, Polo, Tiguan ve Transporter ailesinde bakım, mekanik ve elektronik teşhis.':'Maintenance, mechanical service and electronic diagnostics for Golf, Passat, Polo, Tiguan and Transporter families.','A3, A4, A5, A6 ve Q serilerinde motor, DSG/S tronic ve elektronik sistem kontrolleri.':'Engine, DSG/S tronic and electronic checks for A3, A4, A5, A6 and Q series.','Octavia, Superb, Fabia, Scala, Karoq ve Kodiaq modellerinde planlı bakım ve arıza tespiti.':'Scheduled maintenance and diagnostics for Octavia, Superb, Fabia, Scala, Karoq and Kodiaq.','Leon, Ibiza, Ateca ve Tarraco modellerinde periyodik bakım, yürüyen aksam ve elektronik servis.':'Scheduled maintenance, chassis and electronic service for Leon, Ibiza, Ateca and Tarraco.','Formentor, Leon ve Ateca modellerinde güncel VAG platformlarına uygun kontrol ve bakım.':'Inspection and maintenance for current VAG platforms used by Formentor, Leon and Ateca.',
    'Servis kapsamı':'Service scope','Doğru işlem,':'The right work,','doğru sırayla.':'in the right order.','Randevu sırasında ihtiyacınız olan birden fazla hizmeti seçebilirsiniz. Kesin işlem kapsamı araç kabulü ve teşhis sonrasında, onayınızla belirlenir.':'You can select multiple services while booking. The final scope is set with your approval after intake and diagnosis.',
    'Periyodik bakım':'Scheduled maintenance','Bakım randevusu al →':'Book maintenance →','DSG teşhis ve onarım':'DSG diagnosis and repair','DSG kontrolü seç →':'Choose a DSG check →','Motor ve elektronik':'Engine and electronics','Arıza tespiti seç →':'Choose diagnostics →','Fren, süspansiyon ve klima':'Brakes, suspension and A/C','Birden fazla hizmet seç →':'Select multiple services →',
    'Önce teşhis':'Diagnosis first','Sonra onay':'Approval next','Kayıtlı teslim':'Documented delivery','Sürpriz yok.':'No surprises.','Servis süreci; teşhis, kapsam, onay ve teslim adımlarının birbirinden ayrıldığı açık bir iş akışıyla yürütülür.':'The service journey follows a clear flow separating diagnosis, scope, approval and delivery.',
    'Hizmetler hakkında':'About our services','Bir randevuda birden fazla hizmet seçebilir miyim?':'Can I select multiple services in one booking?','Randevu oluşturunca saat kesinleşmiş olur mu?':'Is the time final when I submit a request?','Hangi saatlerde randevu talebi oluşturabilirim?':'What times can I request?','VAG dışındaki araçlara servis veriliyor mu?':'Do you service vehicles outside VAG?','Evet. VAG araçlarda uzmanız; fakat randevu formundaki “Diğer / Genel” seçeneğiyle farklı marka araçlar için de bakım veya onarım talebi oluşturabilirsiniz.':'Yes. We specialise in VAG vehicles, but you can request maintenance or repair for another make using “Other / General” in the booking form.','Aracın için':'Choose the','doğru adımı seç.':'right step for your car.','Randevu talebi oluştur →':'Submit a booking request →'
  },
  ar: {
    'VAG servis rehberi':'دليل صيانة VAG','VAG teknolojisini bilen servis.':'مركز يفهم تقنيات VAG.',
    'Volkswagen, Audi, Škoda, SEAT ve CUPRA araçların ortak motor, DSG ve elektronik altyapısına odaklanan servis yaklaşımı. Önce teşhis, sonra açık işlem planı ve fiyat onayı.':'خدمة متخصصة في المحركات وناقل DSG والأنظمة الإلكترونية المشتركة بين Volkswagen وAudi وŠkoda وSEAT وCUPRA. التشخيص أولاً، ثم خطة عمل وسعر واضحان.',
    'Yol tarifi':'الاتجاهات','Online randevu başlangıç saatleri':'ساعات بدء الحجز الإلكتروني','Çoklu hizmet':'خدمات متعددة','Tek randevuda birden fazla işlem':'عدة أعمال في موعد واحد','Şeffaf onay':'موافقة واضحة','İşlem öncesi kapsam ve fiyat bilgisi':'النطاق والسعر قبل العمل','VAG odağı':'تركيز VAG','Ortak platform ve teknoloji bilgisi':'خبرة بالمنصات والتقنيات المشتركة',
    'Marka uzmanlığı':'خبرة العلامات','Beş marka,':'خمس علامات،','ortak teknoloji.':'تقنية مشتركة.','VAG grubundaki ortak motor, şanzıman ve elektronik sistem bilgisi; arızayı yalnızca belirti üzerinden değil, sistemin tamamı üzerinden değerlendirmeyi sağlar.':'تتيح خبرتنا بمحركات وناقلات وإلكترونيات VAG تقييم النظام كاملاً لا العَرَض فقط.',
    'Servis kapsamı':'نطاق الخدمة','Doğru işlem,':'العمل الصحيح،','doğru sırayla.':'بالترتيب الصحيح.','Randevu sırasında ihtiyacınız olan birden fazla hizmeti seçebilirsiniz. Kesin işlem kapsamı araç kabulü ve teşhis sonrasında, onayınızla belirlenir.':'يمكنك اختيار عدة خدمات عند الحجز، ويُحدد النطاق النهائي بموافقتك بعد الاستقبال والتشخيص.',
    'Periyodik bakım':'الصيانة الدورية','Bakım randevusu al →':'احجز صيانة ←','DSG teşhis ve onarım':'تشخيص وإصلاح DSG','DSG kontrolü seç →':'اختر فحص DSG ←','Motor ve elektronik':'المحرك والإلكترونيات','Arıza tespiti seç →':'اختر التشخيص ←','Fren, süspansiyon ve klima':'الفرامل والتعليق والمكيّف','Birden fazla hizmet seç →':'اختر عدة خدمات ←',
    'Önce teşhis':'التشخيص أولاً','Sonra onay':'ثم الموافقة','Kayıtlı teslim':'تسليم موثق','Sürpriz yok.':'لا مفاجآت.','Servis süreci; teşhis, kapsam, onay ve teslim adımlarının birbirinden ayrıldığı açık bir iş akışıyla yürütülür.':'تسير الخدمة ضمن خطوات واضحة تفصل التشخيص والنطاق والموافقة والتسليم.',
    'Hizmetler hakkında':'عن الخدمات','Bir randevuda birden fazla hizmet seçebilir miyim?':'هل يمكن اختيار عدة خدمات في موعد واحد؟','Randevu oluşturunca saat kesinleşmiş olur mu?':'هل يصبح الوقت مؤكداً عند إرسال الطلب؟','Hangi saatlerde randevu talebi oluşturabilirim?':'ما ساعات طلب الموعد؟','VAG dışındaki araçlara servis veriliyor mu?':'هل تخدمون سيارات خارج VAG؟','Evet. VAG araçlarda uzmanız; fakat randevu formundaki “Diğer / Genel” seçeneğiyle farklı marka araçlar için de bakım veya onarım talebi oluşturabilirsiniz.':'نعم. نحن متخصصون في VAG، ويمكن طلب صيانة أو إصلاح لعلامة أخرى عبر خيار «أخرى / عام» في نموذج الحجز.','Aracın için':'اختر الخطوة','doğru adımı seç.':'الصحيحة لسيارتك.','Randevu talebi oluştur →':'أرسل طلب موعد ←'
  }
};

Object.assign(window.CICEK_PAGE_TRANSLATIONS.en, {
  'Ana sayfa':'Home','Başakşehir · VAG özel servis':'Başakşehir · VAG specialist service','Aracını tanıyan':'A team that knows','tek ekip.':'your vehicle.','UZMAN SERVİS':'SPECIALIST SERVICE',
  'Motor yağı, filtreler, sıvı seviyeleri ve aracın kilometre planına göre kontrol edilmesi gereken parçalar birlikte değerlendirilir. Kullanılacak ürün ve yapılacak ek işlemler araç sahibinin onayı alınmadan uygulanmaz.':'Engine oil, filters, fluid levels and mileage-based items are assessed together. No product or additional work is applied without the owner’s approval.',
  'Yağ ve filtreler':'Oil and filters','Motor yağı, yağ filtresi, hava ve polen filtresi kontrolü.':'Checks of engine oil, oil filter, air filter and cabin filter.','Sıvı kontrolleri':'Fluid checks','Soğutma, fren ve cam suyu seviyeleri ile kaçak kontrolü.':'Coolant, brake and washer fluid levels plus leak inspection.','Güvenlik kontrolü':'Safety check','Fren, lastik, aydınlatma ve yürüyen aksamın temel kontrolü.':'Basic inspection of brakes, tyres, lighting and chassis.','Bakım kaydı':'Service record','Yapılan işlemlerin ve kullanılan parçaların kayıt altına alınması.':'Recording completed work and parts used.',
  'Geçiş sarsıntısı, kavrama titremesi, gecikmeli hareket veya uyarı lambası gibi belirtilerde önce arıza kayıtları ve sürüş davranışı değerlendirilir. DQ200 ve DQ250 başta olmak üzere DSG sistemlerinde kavrama, mekatronik ve yağ-bakım ihtiyaçları ayrı ayrı incelenir.':'For jerky shifts, clutch vibration, delayed movement or warning lights, fault records and driving behaviour are assessed first. Clutch, mechatronics and fluid needs are inspected separately, especially on DQ200 and DQ250 systems.','Bilgisayarlı teşhis':'Computer diagnostics','Arıza kodları, ölçüm değerleri ve adaptasyon durumunun okunması.':'Reading fault codes, measurement values and adaptation status.','Mekatronik kontrolü':'Mechatronics check','Basınç, valf ve kontrol ünitesi kaynaklı belirtilerin ayrıştırılması.':'Separating symptoms caused by pressure, valves or control units.','Kavrama değerlendirmesi':'Clutch assessment','Aşınma, titreme ve geçiş sorunlarının mekanik kontrolü.':'Mechanical inspection of wear, vibration and shift problems.','Adaptasyon ve test':'Adaptation and test','Uygun işlemler sonrasında temel ayar ve kontrollü yol testi.':'Basic settings and a controlled road test after appropriate work.',
  'Motor performansı, yakıt sistemi, sensörler, ECU iletişimi ve araç içi elektronik ağlar güncel teşhis cihazlarıyla kontrol edilir. Hata kodu tek başına parça değişim gerekçesi sayılmaz; canlı veriler ve mekanik kontrollerle birlikte yorumlanır.':'Engine performance, fuel systems, sensors, ECU communication and onboard networks are checked with current diagnostic equipment. A fault code alone is not treated as a reason to replace a part; it is interpreted with live data and mechanical checks.','OBD arıza taraması':'OBD fault scan','Kontrol ünitelerinin ve kayıtlı hata kodlarının birlikte incelenmesi.':'Combined inspection of control units and stored fault codes.','Canlı veri analizi':'Live data analysis','Sensör, basınç, sıcaklık ve karışım değerlerinin çalışma sırasında kontrolü.':'Checking sensor, pressure, temperature and mixture values while running.','Elektrik ölçümleri':'Electrical measurements','Akü, şarj, kablolama ve bağlantı problemlerinin ölçümlenmesi.':'Measurement of battery, charging, wiring and connection issues.','Motor mekanik kontrolü':'Engine mechanical check','Elektronik verilerin kompresyon, kaçak ve mekanik belirtilerle karşılaştırılması.':'Comparing electronic data with compression, leakage and mechanical symptoms.',
  'Fren sesi, direksiyon titreşimi, süspansiyon vuruntusu veya klima performans kaybı gibi şikâyetler ayrı kontrol adımlarıyla incelenir. Randevu formunda bu işlemlerden birden fazlasını aynı talebe ekleyebilirsiniz.':'Brake noise, steering vibration, suspension knocks and reduced A/C performance are inspected through separate checks. You can add several of these services to one request.','Fren sistemi':'Brake system','Balata, disk, hidrolik ve elektronik fren desteklerinin kontrolü.':'Inspection of pads, discs, hydraulics and electronic brake assistance.','Klima sistemi':'A/C system','Soğutma performansı, kaçak ve kabin filtresi kontrolleri.':'Cooling performance, leakage and cabin filter checks.','Uzun yol veya araç alım öncesi temel güvenlik ve kondisyon taraması.':'Basic safety and condition inspection before a long trip or vehicle purchase.',
  'Belirti ve hata kodu birlikte değerlendirilir; tahmine dayalı parça değişimi yapılmaz.':'Symptoms and fault codes are assessed together; parts are not replaced by guesswork.','İşlem kapsamı ve fiyat bilgisi size iletilir, onayınız olmadan ek işleme başlanmaz.':'The work scope and price are shared; no additional work begins without approval.','Yapılan işlemler ve kullanılan parçalar kayıt altına alınarak araç teslim edilir.':'The vehicle is delivered with the work and parts used recorded.','Evet. Bakım, DSG, motor-elektronik, fren, kaporta ve genel kontrol seçeneklerinden birden fazlasını aynı randevu talebine ekleyebilirsiniz.':'Yes. You can combine maintenance, DSG, engine-electronics, brake, bodywork and inspection services in one request.','Talebiniz servis kayıt sistemine ulaşır. Araç ve işlem kapsamı kontrol edildikten sonra ekip telefon veya WhatsApp üzerinden kesin onay verir.':'Your request reaches the service system. The team confirms it by phone or WhatsApp after checking the vehicle and work scope.','Pazartesi–Cumartesi günleri 09:00–17:00 arasındaki uygun başlangıç saatlerinden seçim yapabilirsiniz. Pazar günleri servis kapalıdır.':'You can choose an available start time between 09:00 and 17:00, Monday to Saturday. We are closed on Sundays.','Hizmetlerini birlikte seç, uygun randevu saatini belirle.':'Choose your services together and select a suitable time.','Talebin doğrudan servis kayıt sistemimize ulaşsın.':'Your request goes directly to our service booking system.','Gizlilik':'Privacy','Kullanım Koşulları':'Terms of Use'
});

Object.assign(window.CICEK_PAGE_TRANSLATIONS.ar, {
  'Ana sayfa':'الرئيسية','Başakşehir · VAG özel servis':'باشاك شهير · مركز VAG متخصص','Aracını tanıyan':'فريق يفهم','tek ekip.':'سيارتك.','UZMAN SERVİS':'مركز متخصص',
  'Golf, Passat, Polo, Tiguan ve Transporter ailesinde bakım, mekanik ve elektronik teşhis.':'صيانة وتشخيص ميكانيكي وإلكتروني لعائلات Golf وPassat وPolo وTiguan وTransporter.','A3, A4, A5, A6 ve Q serilerinde motor, DSG/S tronic ve elektronik sistem kontrolleri.':'فحص المحرك وDSG/S tronic والأنظمة الإلكترونية لطرازات A3 وA4 وA5 وA6 وسلسلة Q.','Octavia, Superb, Fabia, Scala, Karoq ve Kodiaq modellerinde planlı bakım ve arıza tespiti.':'صيانة دورية وتشخيص أعطال لطرازات Octavia وSuperb وFabia وScala وKaroq وKodiaq.','Leon, Ibiza, Ateca ve Tarraco modellerinde periyodik bakım, yürüyen aksam ve elektronik servis.':'صيانة دورية وخدمة الهيكل والإلكترونيات لطرازات Leon وIbiza وAteca وTarraco.','Formentor, Leon ve Ateca modellerinde güncel VAG platformlarına uygun kontrol ve bakım.':'فحص وصيانة متوافقان مع منصات VAG الحديثة لطرازات Formentor وLeon وAteca.',
  'Motor yağı, filtreler, sıvı seviyeleri ve aracın kilometre planına göre kontrol edilmesi gereken parçalar birlikte değerlendirilir. Kullanılacak ürün ve yapılacak ek işlemler araç sahibinin onayı alınmadan uygulanmaz.':'نقيّم زيت المحرك والفلاتر ومستويات السوائل وعناصر الصيانة حسب المسافة معاً، ولا نستخدم منتجاً أو ننفذ عملاً إضافياً دون موافقة المالك.','Yağ ve filtreler':'الزيت والفلاتر','Motor yağı, yağ filtresi, hava ve polen filtresi kontrolü.':'فحص زيت المحرك وفلتر الزيت والهواء وفلتر المقصورة.','Sıvı kontrolleri':'فحص السوائل','Soğutma, fren ve cam suyu seviyeleri ile kaçak kontrolü.':'فحص سائل التبريد والفرامل وغسيل الزجاج والتسرب.','Güvenlik kontrolü':'فحص السلامة','Fren, lastik, aydınlatma ve yürüyen aksamın temel kontrolü.':'فحص أساسي للفرامل والإطارات والإضاءة ونظام التعليق.','Bakım kaydı':'سجل الصيانة','Yapılan işlemlerin ve kullanılan parçaların kayıt altına alınması.':'توثيق الأعمال المنفذة والقطع المستخدمة.',
  'Geçiş sarsıntısı, kavrama titremesi, gecikmeli hareket veya uyarı lambası gibi belirtilerde önce arıza kayıtları ve sürüş davranışı değerlendirilir. DQ200 ve DQ250 başta olmak üzere DSG sistemlerinde kavrama, mekatronik ve yağ-bakım ihtiyaçları ayrı ayrı incelenir.':'عند وجود نتعة أو اهتزاز القابض أو تأخر الحركة أو ضوء تحذير، نراجع سجلات الأعطال وسلوك القيادة أولاً، ثم نفحص القابض والميكاترونيك والزيت كلّاً على حدة، خصوصاً في DQ200 وDQ250.','Bilgisayarlı teşhis':'تشخيص بالحاسوب','Arıza kodları, ölçüm değerleri ve adaptasyon durumunun okunması.':'قراءة رموز الأعطال والقيم وحالة التكيّف.','Mekatronik kontrolü':'فحص الميكاترونيك','Basınç, valf ve kontrol ünitesi kaynaklı belirtilerin ayrıştırılması.':'تمييز الأعراض الناتجة عن الضغط أو الصمامات أو وحدة التحكم.','Kavrama değerlendirmesi':'تقييم القابض','Aşınma, titreme ve geçiş sorunlarının mekanik kontrolü.':'فحص ميكانيكي للتآكل والاهتزاز ومشكلات النقل.','Adaptasyon ve test':'تهيئة واختبار','Uygun işlemler sonrasında temel ayar ve kontrollü yol testi.':'إعداد أساسي واختبار قيادة مراقب بعد العمل المناسب.',
  'Motor performansı, yakıt sistemi, sensörler, ECU iletişimi ve araç içi elektronik ağlar güncel teşhis cihazlarıyla kontrol edilir. Hata kodu tek başına parça değişim gerekçesi sayılmaz; canlı veriler ve mekanik kontrollerle birlikte yorumlanır.':'نفحص أداء المحرك ونظام الوقود والحساسات واتصال ECU والشبكات الإلكترونية بأجهزة حديثة. لا نعتبر رمز العطل وحده سبباً لتبديل القطعة، بل نربطه بالبيانات الحية والفحص الميكانيكي.','OBD arıza taraması':'مسح أعطال OBD','Kontrol ünitelerinin ve kayıtlı hata kodlarının birlikte incelenmesi.':'فحص وحدات التحكم ورموز الأعطال المسجلة معاً.','Canlı veri analizi':'تحليل البيانات الحية','Sensör, basınç, sıcaklık ve karışım değerlerinin çalışma sırasında kontrolü.':'فحص قيم الحساسات والضغط والحرارة والخليط أثناء التشغيل.','Elektrik ölçümleri':'قياسات كهربائية','Akü, şarj, kablolama ve bağlantı problemlerinin ölçümlenmesi.':'قياس البطارية والشحن والأسلاك ومشكلات التوصيل.','Motor mekanik kontrolü':'فحص ميكانيكي للمحرك','Elektronik verilerin kompresyon, kaçak ve mekanik belirtilerle karşılaştırılması.':'مقارنة البيانات الإلكترونية بالضغط والتسرب والأعراض الميكانيكية.',
  'Fren sesi, direksiyon titreşimi, süspansiyon vuruntusu veya klima performans kaybı gibi şikâyetler ayrı kontrol adımlarıyla incelenir. Randevu formunda bu işlemlerden birden fazlasını aynı talebe ekleyebilirsiniz.':'نفحص صوت الفرامل واهتزاز المقود وضربات التعليق وضعف المكيّف بخطوات مستقلة، ويمكن جمع عدة خدمات في طلب واحد.','Fren sistemi':'نظام الفرامل','Balata, disk, hidrolik ve elektronik fren desteklerinin kontrolü.':'فحص البطانات والأقراص والهيدروليك وأنظمة دعم الفرامل.','Klima sistemi':'نظام المكيّف','Soğutma performansı, kaçak ve kabin filtresi kontrolleri.':'فحص أداء التبريد والتسرب وفلتر المقصورة.','Uzun yol veya araç alım öncesi temel güvenlik ve kondisyon taraması.':'فحص أساسي للسلامة والحالة قبل السفر أو شراء السيارة.',
  'Belirti ve hata kodu birlikte değerlendirilir; tahmine dayalı parça değişimi yapılmaz.':'نقيّم العَرَض ورمز العطل معاً ولا نبدّل القطع بالتخمين.','İşlem kapsamı ve fiyat bilgisi size iletilir, onayınız olmadan ek işleme başlanmaz.':'نرسل نطاق العمل والسعر ولا نبدأ عملاً إضافياً دون موافقتك.','Yapılan işlemler ve kullanılan parçalar kayıt altına alınarak araç teslim edilir.':'تُسلّم السيارة مع توثيق الأعمال والقطع المستخدمة.','Evet. Bakım, DSG, motor-elektronik, fren, kaporta ve genel kontrol seçeneklerinden birden fazlasını aynı randevu talebine ekleyebilirsiniz.':'نعم، يمكنك جمع الصيانة وDSG والمحرك والإلكترونيات والفرامل والهيكل والفحص العام في طلب واحد.','Talebiniz servis kayıt sistemine ulaşır. Araç ve işlem kapsamı kontrol edildikten sonra ekip telefon veya WhatsApp üzerinden kesin onay verir.':'يصل طلبك إلى نظام الصيانة، ويؤكده الفريق عبر الهاتف أو واتساب بعد مراجعة السيارة ونطاق العمل.','Pazartesi–Cumartesi günleri 09:00–17:00 arasındaki uygun başlangıç saatlerinden seçim yapabilirsiniz. Pazar günleri servis kapalıdır.':'يمكن اختيار وقت بدء متاح بين 09:00 و17:00 من الإثنين إلى السبت، والمركز مغلق الأحد.','Hizmetlerini birlikte seç, uygun randevu saatini belirle.':'اختر خدماتك معاً وحدد الوقت المناسب.','Talebin doğrudan servis kayıt sistemimize ulaşsın.':'سيصل طلبك مباشرة إلى نظام حجز الصيانة.','Gizlilik':'الخصوصية','Kullanım Koşulları':'شروط الاستخدام'
});

Object.assign(window.CICEK_PAGE_TRANSLATIONS.en, {
  'Hayır. Talebiniz servis kayıt sistemine ulaşır. Araç ve işlem kapsamı kontrol edildikten sonra kesin onay e-posta adresinize iletilir.':'No. Your request reaches the service system first. The final confirmation is emailed after the vehicle and work scope are checked.'
});

Object.assign(window.CICEK_PAGE_TRANSLATIONS.ar, {
  'Hayır. Talebiniz servis kayıt sistemine ulaşır. Araç ve işlem kapsamı kontrol edildikten sonra kesin onay e-posta adresinize iletilir.':'لا. يصل طلبك أولاً إلى نظام الصيانة، ثم يُرسل التأكيد النهائي إلى بريدك الإلكتروني بعد مراجعة السيارة ونطاق العمل.'
});
